<a href="https://colab.research.google.com/github/10100111/Display-of-HW1/blob/main/69_Ultra_Lite_TensorFlow_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Задание Ultra Lite

Макс 10 баллов

1. Создайте трехмерный тензор из массива случайных чисел.

2. Создайте два тензора: один 2х3, второй 3х4. Умножьте их с помощью функции, затем с помощью оператора матричного умножения, сравните результаты.

3. Создайте ragged тензор. Выведите, на каком устройстве он располагается.

In [9]:
# Загрузка бблиотек
import tensorflow as tf # импортируем модуль tensorflow

In [10]:
# Создание трезмерного тензора
tensor3d = tf.random.uniform([3, 3, 3])
tensor3d

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[9.58584309e-01, 9.66389775e-01, 7.17539787e-02],
        [9.19598699e-01, 9.15038586e-03, 8.91460657e-01],
        [3.45587730e-04, 9.37341332e-01, 8.22578907e-01]],

       [[5.28843164e-01, 3.19306970e-01, 3.73931766e-01],
        [8.88266444e-01, 1.05351806e-01, 3.23573709e-01],
        [4.27358985e-01, 4.80396628e-01, 3.87683034e-01]],

       [[5.59172153e-01, 4.76481557e-01, 2.97854900e-01],
        [1.81133270e-01, 5.01070857e-01, 7.98372030e-02],
        [4.43899512e-01, 1.86643124e-01, 3.84238958e-01]]], dtype=float32)>

In [11]:
# Создание тензоров: один 2х3, второй 3х4
tensor2x3 = tf.random.normal([2, 3])
tensor3x4 = tf.random.normal([3, 4])
print(tensor2x3)
print()
print(tensor3x4)

tf.Tensor(
[[-1.7561916   0.40790635  0.09731789]
 [-0.05743969 -1.2366548  -0.4065547 ]], shape=(2, 3), dtype=float32)

tf.Tensor(
[[ 0.26737195 -0.9796032  -0.23088    -0.8376535 ]
 [ 2.6825826   1.63271    -0.95461106  0.06001246]
 [ 0.1549044   0.48523396 -0.99304616  0.8258599 ]], shape=(3, 4), dtype=float32)


In [12]:
# Перемножение с помощью функции
tensorMatmul = tf.matmul(tensor2x3, tensor3x4)
print(tensorMatmul)

tf.Tensor(
[[ 0.63976103  2.4335856  -0.08056355  1.5759305 ]
 [-3.3957634  -2.1601045   1.5975137  -0.36185735]], shape=(2, 4), dtype=float32)


In [13]:
# Перемножение с помощью оператора
tensorOperator = tensor2x3 @ tensor3x4
print(tensorOperator)


tf.Tensor(
[[ 0.63976103  2.4335856  -0.08056355  1.5759305 ]
 [-3.3957634  -2.1601045   1.5975137  -0.36185735]], shape=(2, 4), dtype=float32)


In [14]:
# Создание ragged тензора
xRagged = tf.RaggedTensor.from_row_lengths(values=[23, 15 ,14, 16, 17, 99, 85, 13, 58, 75, 100],
                                                row_lengths=[2, 1, 3, 5, 0, 0])
print(xRagged)

<tf.RaggedTensor [[23, 15], [14], [16, 17, 99], [85, 13, 58, 75, 100], [], []]>


In [15]:
# Выведем список устройств 
print(tf.config.experimental.list_physical_devices())

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'), PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]


In [16]:
# Вывод, на каком устройстве он располагается
print(xRagged.values.device.endswith('GPU:0'))

True


In [21]:
# Без метода .values не работает метод .devicе для рваных тензоров
xRagged.values

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 23,  15,  14,  16,  17,  99,  85,  13,  58,  75, 100], dtype=int32)>

.values вывел все значения в виде одного списка из рваного тензора

In [22]:
# Посмотрим какие вообще доступны методы для рваного тензора
dir(xRagged)

['__abs__',
 '__abstractmethods__',
 '__add__',
 '__and__',
 '__bool__',
 '__class__',
 '__composite_gradient__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__invert__',
 '__le__',
 '__lt__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rfloordiv__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__tf_tracing_type__',
 '__truediv__',
 '__weakref__',
 '__xor__',
 '_abc_impl',
 '_as_graph_element',
 '_consumers',
 '_convert_values_and_partition',
 '_eager_value',
 '_from_nested_row_partitions',
 '_from_row_partition',
 '_from_variant',
 '_i